# Generated by Django 5.1.6 on 2025-02-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smartly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smartly.course')),
            ],
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('courseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Smartly.courseproperty')),
            ],
            bases=('Smartly.courseproperty',),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('courseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Smartly.courseproperty')),
            ],
            bases=('Smartly.courseproperty',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('courseproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Smartly.courseproperty')),
            ],
            bases=('Smartly.courseproperty',),
        ),
    ]
