# Generated by Django 3.0.5 on 2025-02-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smartly', '0003_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='courseproperty',
            name='discription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='courseproperty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=100),
        ),
    ]
